--- 
- name: Setup web server
  hosts: all
  become: yes
  
  vars:
    variable_to_be_replaced: 'Apache on CLOUD'
    inline_variable: "{{ inventory_hostname }}"
  
  
  tasks: 
     
    - name : Install web server
      yum:
        name: httpd
        state:  installed
    
    - name: Setup Index.html
      template:
        src:  msg.j2
        dest: /var/www/html/index.html

    - name: web service 
      service:
        name: httpd
        enabled:  yes
        state: started
